const { listPaths } = require("./src/plugins/components");
//
// let inputs_docs = listPaths("inputs");
// let processors_docs = listPaths("processors");
// let outputs_docs = listPaths("outputs");
// let caches_docs = listPaths("caches");
// let rate_limits_docs = listPaths("rate_limits");
// let buffers_docs = listPaths("buffers");
// let metrics_docs = listPaths("metrics");
// let tracers_docs = listPaths("tracers");

// let components = listPaths();

module.exports = {
  tutorials: [
    "tutorials/basics",
    "tutorials/studio",
    "tutorials/data",
    "tutorials/growth",
    "tutorials/inbox",
    "tutorials/engage",
    "tutorials/integrations",
    "tutorials/webinars",
  ],
  cookbooks: [
    "cookbooks/getting_started",
    "cookbooks/conversation-design",
    {
      type: "category",
      label: "Basic",
      items: ["cookbooks/multilingual"],
    },
    {
      type: "category",
      label: "Understanding channels 101",
      collapsed: true,
      items: [
        "cookbooks/Understanding channels 101/whatsapp-chatbot-101",
        "cookbooks/Understanding channels 101/fbm-chatbot-101",
        "cookbooks/Understanding channels 101/gbm-chatbot-101",
        "cookbooks/Understanding channels 101/email-outbound-101",
        "cookbooks/Understanding channels 101/sms-india-101",
      ],
    },
    {
      type: "category",
      label: "Template Bots",
      collapsed: true,
      items: [
        "cookbooks/template-bots/model-bot",
        // "cookbooks/template-bots/customer-support-bot",
        "cookbooks/template-bots/customer-support-bot",
        "cookbooks/template-bots/faq",
        "cookbooks/template-bots/lead-generation",
      ],
    },
    {
      type: "category",
      label: "All About Whatsapp Bots",
      collapsed: true,
      items: [
        "cookbooks/whatsapp cookbook/whatsapp-bot",
        "cookbooks/whatsapp cookbook/whatsapp-notification-template",
        "cookbooks/whatsapp cookbook/whatsapp-notification-ym",
        "cookbooks/whatsapp cookbook/whatsapp-guidelines",
        "cookbooks/whatsapp cookbook/fb-business-verification",
        "cookbooks/whatsapp cookbook/wa-migration",
        "cookbooks/whatsapp cookbook/wa-capturing-qr-event",
        "cookbooks/whatsapp cookbook/faqs",
      ],
    },
  ],

  platform_concepts: [
    "platform_concepts/getting-started",
    {
      type: "category",
      label: "Studio",
      collapsed: true,
      items: [
        "platform_concepts/studio/overview",
        "platform_concepts/studio/journeys",
        {
          type: "category",
          label: "Nodes",
          collapsed: true,
          items: [
            "platform_concepts/studio/steps/steps",
            "platform_concepts/studio/steps/prompts-and-messages",
            "platform_concepts/studio/steps/action-nodes-and-logic",
          ],
        },

        {
          type: "category",
          label: "Natural Language Understanding",
          collapsed: true,
          items: [
            "platform_concepts/studio/natural-language-understanding/intents",
            "platform_concepts/studio/natural-language-understanding/entities",
          ],
        },
        {
          type: "category",
          label: "Knowledge Management",
          collapsed: true,
          items: [
            "platform_concepts/studio/knowledge-management/add-faqs",
            "platform_concepts/studio/knowledge-management/what-is-document-cognition",
            "platform_concepts/studio/knowledge-management/AWS",
            "platform_concepts/studio/knowledge-management/Sharepoint",
          ],
        },
        {
          type: "category",
          label: "API Management",
          collapsed: true,
          items: [
            "platform_concepts/studio/api-management/add-api",
            "platform_concepts/studio/api-management/send-data",
            "platform_concepts/studio/api-management/receive-data",
            "platform_concepts/studio/api-management/enviroment-variables",
            "platform_concepts/studio/api-management/bearer-token",
            "platform_concepts/studio/api-management/transformation-function",
          ],
        },
        {
          type: "category",
          label: "Context Management",
          collapsed: true,
          items: [
            "platform_concepts/studio/context-management/add-contextual-response",
          ],
        },

        "platform_concepts/studio/languages-supported",
        "platform_concepts/studio/tools",
        "platform_concepts/studio/event-hub",
        "platform_concepts/studio/bot-variables",
        "platform_concepts/studio/bot-training",
        "platform_concepts/studio/cloud-function",
        "platform_concepts/studio/modes",
      ],
    },
    {
      type: "category",
      label: "Data",
      collapsed: true,
      items: [
        "platform_concepts/data/create-tables",
        "platform_concepts/data/database-search",
      ],
    },
    {
      type: "category",
      label: "Insights",
      collapsed: true,
      items: [
        "platform_concepts/growth/growth",
        "platform_concepts/growth/overview",
        "platform_concepts/growth/metrics",
        "platform_concepts/growth/funnels",
        "platform_concepts/growth/api-usage",
      ],
    },
    {
      type: "category",
      label: "Inbox",
      collapsed: true,
      items: [
        "platform_concepts/inbox/inbox",
        "platform_concepts/inbox/manage-support-agent",
        "platform_concepts/inbox/tickets-assignment-logic",
        "platform_concepts/inbox/default-agent-statuses",
        "platform_concepts/inbox/inbox-settings/custom-usecases",

        {
          type: "category",
          label: "Inbox Settings",
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Chat Configuration",
              collapsed: true,
              items: [
                "platform_concepts/inbox/inbox-settings/chats-configuration/tags",
                "platform_concepts/inbox/inbox-settings/chats-configuration/chat-timeout",
                "platform_concepts/inbox/inbox-settings/chats-configuration/custom-fields",
                "platform_concepts/inbox/inbox-settings/chats-configuration/csat",
                "platform_concepts/inbox/inbox-settings/chats-configuration/chat-queue",
                "platform_concepts/inbox/inbox-settings/chats-configuration/offline-chat",
                "platform_concepts/inbox/inbox-settings/chats-configuration/email-transcript",
                "platform_concepts/inbox/inbox-settings/chats-configuration/chat-autotranslate",
              ],
            },
            {
              type: "category",
              label: "Agent Configuration",
              collapsed: true,
              items: [
                "platform_concepts/inbox/inbox-settings/agent-configuration/agent-settings",
                "platform_concepts/inbox/inbox-settings/agent-configuration/working-hours",
              ],
            },
            "platform_concepts/inbox/inbox-settings/productivity-tools",
            "platform_concepts/inbox/inbox-settings/security",
            "platform_concepts/inbox/inbox-settings/groups",
          ],
        },
        {
          type: "category",
          label: "Mobile SDK",
          collapsed: true,
          items: [
            "platform_concepts/inbox/mobilesdk/android",
            "platform_concepts/inbox/mobilesdk/cordova",
          ],
        },
        {
          type: "category",
          label: "Chats",
          collapsed: true,
          items: [
            "platform_concepts/inbox/inbox-settings/chats-configuration/types-of-chat",
            "platform_concepts/inbox/whatsapp-24hr-window-policy",
            "platform_concepts/inbox/Chat agent activity report",
            "platform_concepts/inbox/Chat agent performance report",
            "platform_concepts/inbox/Chat archives report",
            "platform_concepts/inbox/Chat report metrics 101",
            "platform_concepts/inbox/Chat auto translate",
            "platform_concepts/inbox/google-translate-api-inbox",
            "platform_concepts/inbox/Chat custom fields",
            "platform_concepts/inbox/Chat working hours",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Engagement",
      collapsed: true,
      items: [
        "platform_concepts/engagement/engage",
        {
          type: "category",
          label: "Outbound Engagement",
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Templates",
              collapsed: true,
              items: [
                "platform_concepts/engagement/outbound/templates/overview",
                "platform_concepts/engagement/outbound/templates/sms-template",
                "platform_concepts/engagement/outbound/templates/email-template",
                "platform_concepts/engagement/outbound/templates/whatsapp-template",
              ],
            },
            {
              type: "category",
              label: "Campaigns",
              collapsed: true,
              items: [
                "platform_concepts/engagement/outbound/outbound-campaigns/email-campaign",
                "platform_concepts/engagement/outbound/outbound-campaigns/sms-campaign",
                "platform_concepts/engagement/outbound/outbound-campaigns/whatsapp-campaign",
                "platform_concepts/engagement/outbound/outbound-campaigns/run-campaign",
              ],
            },
            "platform_concepts/engagement/outbound/filter",
            "platform_concepts/engagement/outbound/notification-engine",
          ],
        },
        {
          type: "category",
          label: "Inbound Engagement",
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Getting Started",
              collapsed: true,
              items: [
                "platform_concepts/engagement/inbound/gettingStarted/launchingYourFirstInboundCampaign",
                "platform_concepts/engagement/inbound/gettingStarted/campaignsOverviewScreen",
                "platform_concepts/engagement/inbound/gettingStarted/testingInboundCampaign",
              ],
            },
            {
              type: "category",
              label: "Inbound Widgets",
              collapsed: true,
              items: [
                "platform_concepts/engagement/inbound/inboundWidgets/typesOfWidgetsAndWidgetConfigurations",
                "platform_concepts/engagement/inbound/inboundWidgets/embedWidgetsOnWebsite",
                "platform_concepts/engagement/inbound/inboundWidgets/embedWidgetsOnShopify",
              ],
            },
            {
              type: "category",
              label: "Web Behaviour Triggers (When)",
              collapsed: true,
              items: [
                "platform_concepts/engagement/inbound/webBehaviourTriggers/webBehaviorTriggerType",
                "platform_concepts/engagement/inbound/webBehaviourTriggers/webBehaviorsInEcomm",
                "platform_concepts/engagement/inbound/webBehaviourTriggers/webBehaviorsInContentMarketing",
              ],
            },
            {
              type: "category",
              label: "Audience Targeting (Who)",
              collapsed: true,
              items: [
                "platform_concepts/engagement/inbound/audienceTargetting/audienceTargetingRules",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Channel Configuration",
      collapsed: true,
      items: [
        "platform_concepts/channelConfiguration/alexa",
        "platform_concepts/channelConfiguration/android",
        "platform_concepts/channelConfiguration/cordova",
        "platform_concepts/channelConfiguration/email-outbound",
        "platform_concepts/channelConfiguration/facebook-messenger",
        "platform_concepts/channelConfiguration/fb-lead-ads",
        "platform_concepts/channelConfiguration/fb-workplace",
        "platform_concepts/channelConfiguration/flutter",
        "platform_concepts/channelConfiguration/generic-webhook",
        "platform_concepts/channelConfiguration/google-assistant",
        "platform_concepts/channelConfiguration/googleChat",
        "platform_concepts/channelConfiguration/instagram",
        "platform_concepts/channelConfiguration/ios",
        "platform_concepts/channelConfiguration/ivr-bots",
        "platform_concepts/channelConfiguration/react-native",
        "platform_concepts/channelConfiguration/slack",
        "platform_concepts/channelConfiguration/sms-outbound-india",
        "platform_concepts/channelConfiguration/teams",
        "platform_concepts/channelConfiguration/telegram",
        "platform_concepts/channelConfiguration/web-widget",
        "platform_concepts/channelConfiguration/web",
        "platform_concepts/channelConfiguration/whatsapp-configuration",
        "platform_concepts/channelConfiguration/xamarin",
      ],
    },
    {
      type: "category",
      label: "Integrations",
      collapsed: true,
      items: [
        "platform_concepts/appConfiguration/azure-ad",
        "platform_concepts/appConfiguration/camspay",
        "platform_concepts/appConfiguration/freshdesk",
        "platform_concepts/appConfiguration/google-calendar",
        "platform_concepts/appConfiguration/google-sheets",
        "platform_concepts/appConfiguration/hubspot-crm",
        "platform_concepts/appConfiguration/intercom-livechat",
        "platform_concepts/appConfiguration/microsoft-dynamics",
        "platform_concepts/appConfiguration/microsoft-graph",
        "platform_concepts/appConfiguration/payuBiz",
        "platform_concepts/appConfiguration/power-bi",
        "platform_concepts/appConfiguration/razorpay",
        "platform_concepts/appConfiguration/salesforce-service-cloud",
        "platform_concepts/appConfiguration/service-now",
        "platform_concepts/appConfiguration/sftp",
        "platform_concepts/appConfiguration/shopify",
        "platform_concepts/appConfiguration/stripe",
        "platform_concepts/appConfiguration/successfactors",
        "platform_concepts/appConfiguration/zalo",
        "platform_concepts/appConfiguration/zendesk-sunshine",
        "platform_concepts/appConfiguration/zendesk",
        "platform_concepts/appConfiguration/zoho-crm",
        "platform_concepts/appConfiguration/zoho-live-chat",
        "platform_concepts/appConfiguration/twilio-verify",
      ],
    },
    {
      type: "category",
      label: "Configurations",
      collapsed: true,
      items: [
        "platform_concepts/configurations/signup-post-bot-invite",
        "platform_concepts/configurations/access-management",
        "platform_concepts/configurations/subscription",
        "platform_concepts/configurations/api-keys",
      ],
    },
    {
      type: "category",
      label: "Compliances",
      collapsed: true,
      items: ["platform_concepts/compliances/certifications"],
    },
  ],
  updates: [
    "updates/overview",
    {
      type: "category",
      label: "August 2021",
      collapsed: true,
      items: [
        "updates/aug_21/analytics",
        "updates/aug_21/builder",
        "updates/aug_21/inbox",
      ],
    },
    {
      type: "category",
      label: "September 2021",
      collapsed: true,
      items: ["updates/sep_21/engage", "updates/sep_21/inbox"],
    },
    {
      type: "category",
      label: "October 2021",
      collapsed: true,
      items: ["updates/oct_21/engage", "updates/oct_21/inbox"],
    },
  ],
  glossary: [
    // "glossary/advanced-virtual-assistants",
    // "glossary/agent-assist",

    {
      type: "category",
      label: "CAIP",
      collapsed: false,
      items: [
        "glossary/advanced-virtual-assistants",
        "glossary/chatbot",
        "glossary/conversational-ai",
        "glossary/conversational-history",
        "glossary/cpaas",
        "glossary/csat",
        "glossary/customer-engagement",
        "glossary/customer-experience",
        "glossary/multimodal-capabilities",
        "glossary/total-experience-automation",
        "glossary/virtual-assistant",
        "glossary/voice-only",
      ],
    },
    {
      type: "category",
      label: "Product",
      collapsed: true,
      items: [
        "glossary/agent-assist",
        "glossary/behaviour-prediction",
        "glossary/biometric-authentication",
        "glossary/bot-fallback",
        "glossary/clarifying-dialogue",
        "glossary/compound-response-generation",
        "glossary/contextualization",
        "glossary/custom-UI",
        "glossary/customer-experience-automation",
        "glossary/human-fallback",
        "glossary/human-to-bot-handover",
        "glossary/intent-marketplace",
        "glossary/intermediary-dialogue",
        "glossary/language-support",
        "glossary/language-variant",
        "glossary/multimodal-rendering",
        "glossary/omnichannel",
        "glossary/orchestration",
        "glossary/parked-intents",
        "glossary/personalization",
        "glossary/pinpoint-improvements",
        "glossary/pretrained-intents",
        "glossary/proactive-conversations",
        "glossary/propose-improvements",
        "glossary/quality-assurance",
        "glossary/reinforcement-learning",
        "glossary/self-service-routing",
        "glossary/small-talk-handling",
        "glossary/text-to-speech",
      ],
    },
    {
      type: "category",
      label: "Channel",
      collapsed: true,
      items: ["glossary/chat", "glossary/rich-communication-service"],
    },
    {
      type: "category",
      label: "Product - Integrations",
      collapsed: true,
      items: [
        "glossary/bot-to-bot-communication-using-natural-language",
        "glossary/capability-directory",
        "glossary/custom-integration",
        "glossary/custom-intent-registry",
        "glossary/decision-tree-node-integration",
        "glossary/integration-platform",
        "glossary/keyword-or-phrase-matching",
        "glossary/second-third-party-user-data",
      ],
    },
    {
      type: "category",
      label: "Engineering",
      collapsed: true,
      items: [
        "glossary/confirmational-cues",
        "glossary/deferred-handling",
        "glossary/deferred-intent",
        "glossary/expression-and-behavior-rendering",
        "glossary/full-duplex-handling",
        "glossary/knowledge-extraction",
        "glossary/knowledge-mapping",
        "glossary/language-decomposition",
        "glossary/language-detection",
        "glossary/modality-switching",
        "glossary/natural-language-generation",
        "glossary/process-mapping",
        "glossary/script-generation",
        "glossary/search",
        "glossary/search-and-summarization",
        "glossary/sentence-rewriting",
        "glossary/sentiment-analysis",
        "glossary/supervised-learning-loop",
        "glossary/voice-synthesis",
      ],
    },
  ],
};
